#!/bin/sh
# This script saves the environment variables of the SSH agent in the file
# .ssh/latestagent for tmux to read when attaching.
# See this stack exchange answer: http://unix.stackexchange.com/a/114597

SSHVARS="SSH_CLIENT SSH_TTY SSH_AUTH_SOCK SSH_CONNECTION DISPLAY"

for var in ${SSHVARS} ; do
  echo "export $var=\"$(eval echo '$'$var)\""
done 1>$HOME/.ssh/latestagent
