#############################################################################################
# These should be defaults.
[[rule]]
toolName = "activate_skill"
decision = "allow"
priority = 100

[[rule]]
toolName = "read_file"
argsPattern = '"file_path":"/tmp/,'
decision = "allow"
priority = 100

# Pseudo-YOLO.
[[rule]]
toolName = ["write_file", "replace"]
decision = "allow"
priority = 100

#############################################################################################
# SDLC specific rules

[[rule]]
toolName = "run_shell_command"
commandPrefix = "gh"
decision = "allow"
priority = 100

[[rule]]
toolName = "run_shell_command"
commandRegex = "(ruff|ty|pytest)\\b.*"
decision = "allow"
priority = 100

# Most repositories are Jujutsu, so use jj, not git.
[[rule]]
toolName = "run_shell_command"
commandRegex = "git\\b.*"
decision = "deny"
deny_message = "Use jj instead of git to interact with the repository. If this is not a Jujutsu repository, ask user."
priority = 200

[[rule]]
toolName = "run_shell_command"
commandRegex = "jj\\s+(log|status|describe|new|edit|show|diff)\\b.*"
decision = "allow"
priority = 200

# Openspec commands.
[[rule]]
toolName = "run_shell_command"
commandRegex = "openspec\\s+(status|instructions)\\b.*"
decision = "allow"
priority = 200

# Jira commands.
[[rule]]
toolName = "run_shell_command"
commandPrefix = "jira"
decision = "allow"
priority = 200

#############################################################################################
# Python package management

# Never use bare pip.
[[rule]]
toolName = "run_shell_command"
commandRegex = "pip\\b.*"
decision = "deny"
deny_message = "Never use pip directly. Use `uv run --with <package> ...` instead or `uv pip ...`. If you don't have uv installed, ask user."
priority = 200

# Never, ever use uv pip install with --system or --break-system-packages.
[[rule]]
toolName = "run_shell_command"
commandRegex = ".*uv\\s+pip\\s+install.*(--system|--break-system-packages).*"
decision = "deny"
deny_message = "Never ever use uv pip install with --system or --break-system-packages. ALWAYS use a virtual environment. If you don't have uv installed, ask user."
priority = 250

#############################################################################################
# Behavioral rules
# Gemini is unable to follow instructions, so we encode them as rules.

# Stop using shell redirection.
[[rule]]
toolName = "run_shell_command"
commandRegex = ".*([^2]|^)>|.*<.*"
decision = "deny"
deny_message = "MANDATORY: never use shell redirection if you can use one of the available tool instead"
priority = 300

# Gemini is not trushworthy.
[[rule]]
toolName = "run_shell_command"
commandRegex = "rm(?![^\"]* (?!-|test_)[^\\s\"])[^\"]*\""
decision = "allow"
priority = 250

[[rule]]
toolName = "run_shell_command"
commandRegex = ".*\\brm\\b.*"
decision = "ask_user"
priority = 200

# Gemini not being trustworth, I certainly won't allow it to mess with my history.
[[rule]]
toolName = "run_shell_command"
commandRegex = ".*\\bjj\\s+(absorb|rebase|squash|amend|abandon|edit|split|unsquash|restore|undo|op|git).*$"
decision = "ask_user"
priority = 200
