[[rule]]
toolName = "run_shell_command"
commandRegex = "rm(?![^\"]* (?!-|test_)[^\\s\"])[^\"]*\""
decision = "allow"
priority = 250

[[rule]]
toolName = "run_shell_command"
commandRegex = ".*\\brm\\b.*"
decision = "ask_user"
priority = 200

[[rule]]
toolName = "run_shell_command"
commandRegex = ".*\\bjj\\s+(absorb|rebase|squash|amend|abandon|edit|split|unsquash|restore|undo|op).*$"
decision = "ask_user"
priority = 200

[[rule]]
toolName = "run_shell_command"
commandRegex = "jj\\s+git\\b.*"
decision = "allow"
priority = 250

[[rule]]
toolName = "run_shell_command"
commandRegex = ".*"
decision = "allow"
priority = 100

[[rule]]
toolName = "activate_skill"
decision = "allow"
priority = 100

[[rule]]
toolName = "read_file"
decision = "allow"
priority = 100

[[rule]]
toolName = ["write_file", "replace"]
decision = "allow"
priority = 100

[[rule]]
toolName = "run_shell_command"
commandRegex = ".*([^2]|^)>|.*<.*"
decision = "deny"
deny_message = "MANDATORY: never use shell redirection if you can use one of the available tool instead"
priority = 300

[[rule]]
toolName = "run_shell_command"
commandRegex = ".*uv\\s+pip\\s+install.*(--system|--break-system-packages).*"
decision = "deny"
deny_message = "Never ever use uv pip install with --system or --break-system-packages. ALWAYS use a virtual environment. If you don't have uv installed, ask user."
priority = 250
