[[rule]]
toolName = "run_shell_command"
commandRegex = ".*"
decision = "allow"
priority = 100

[[rule]]
toolName = "activate_skill"
decision = "allow"
priority = 100

[[rule]]
toolName = "read_file"
decision = "allow"
priority = 100

[[rule]]
toolName = "write_file"
decision = "allow"
priority = 100
