languages:
  python:
    linters:
      - "ruff format"
      - "ruff check --output-format concise" 

  javascript:
    linters:
      - "eslint"
      - "prettier --check"

  typescript:
    linters:
      - "eslint"
      - "tsc --noEmit"
      - "prettier --check"

  rust:
    linters:
      - "cargo clippy"
      - "cargo fmt --check"

  go:
    linters:
      - "go fmt"
      - "go vet"
      - "golint"

  shell:
    linters:
      - "shellcheck"

  yaml:
    linters:
      - "yamllint"

  dockerfile:
    linters:
      - "hadolint"
  sql:
    linters:
      - "sqlfluff format"
      - "sqlfluff lint"
